---
- hosts: all
  become: yes

  tasks:
  - selinux: state=disabled
  - copy: content="overlay" dest=/etc/modules-load.d/overlay.conf
  - copy:
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
      dest: /usr/lib/sysctl.d/90-system.conf

  - yum: name={{ item }} state=present update_cache=yes
    with_items:
     - bridge-utils
     - conntrack-tools

  - yum: name=* state=latest
