apiVersion: v1
kind: Service
metadata:
  name: grafana-ext
  labels:
    name: grafana-ext
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
  selector:
    component: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-ext
  labels:
    name: prometheus-ext
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30909
  selector:
    app: prometheus
[centos@ip-172-20-0-15 ~]$
[centos@ip-172-20-0-15 ~]$ cat nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-ext
  labels:
    name: grafana-ext
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
  selector:
    component: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-ext
  labels:
    name: prometheus-ext
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30909
  selector:
    app: prometheus